name: Issue Notifier  # 워크플로우의 이름을 Issue Notifier로 설정

on:
  issues:
    types: [opened]  # 새로운 이슈가 열릴 때 이 워크플로우가 실행됨

jobs:
  notify:
    runs-on: ubuntu-latest  # 최신 우분투 환경에서 실행

    steps:
      - name: Notify about new issue  # 첫 번째 단계: 이슈 알림
        run: echo "A new issue has been opened!"  # "이슈가 생성되었습니다!" 메시지를 출력
